name: ShellCheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ShellCheck
        run: sudo apt-get install shellcheck

      - name: Run ShellCheck on Common
        run: shellcheck scripts/common.sh
        
      - name: Run ShellCheck on Master Scriopt
        run: shellcheck scripts/master.sh
